client_socket( function () print('TRACE:client_socket') end )
client_sendmsg( function () print('TRACE:client_sendmsg') end )
client_recvmsg( function () print('TRACE:client_recvmsg') end )
client_recverr( function () print('TRACE:client_recverr') end )
client_close( function () print('TRACE:client_close') end )

server_socket( function () print('TRACE:server_socket') end )
server_sendmsg( function () print('TRACE:server_sendmsg') end )
server_recvmsg( function () print('TRACE:server_recvmsg') end )
server_recverr( function () print('TRACE:server_recverr') end )
server_close( function () print('TRACE:server_close') end )
