client_socket( function () print('TRACE:client_socket') end )
client_sendmsg( function () print('TRACE:client_sendmsg'); return 0 end )
client_recvmsg( function () print('TRACE:client_recvmsg'); return 0 end )
client_recverr( function () print('TRACE:client_recverr'); return 0 end )
client_close( function () print('TRACE:client_close') end )

server_socket( function () print('TRACE:server_socket') end )
server_sendmsg( function () print('TRACE:server_sendmsg'); return 0 end )
server_recvmsg( function () print('TRACE:server_recvmsg'); return 0 end )
server_recverr( function () print('TRACE:server_recverr'); return 0 end )
server_close( function () print('TRACE:server_close') end )
